name: "Hugo Site CI"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Download content and theme files"
        run: './download-files.sh'
      - name: "Set up Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: "Build the site with Hugo"
        run: 'hugo --baseURL https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/'
      - name: "Upload the site as an artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public/"

  deploy:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: build
    concurrency:
      group: 'github-pages'
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy the site to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v1
